### ISSUE TITLE
Handle slf4j-jdk14 in enforceLogback()

### ISSUE THREAD

**Issue by paskos** [ljacomet/logging-capabilities#23] opened 2022-07-27 08:08 UTC
enforceLogback() does not handle org.slf4j:slf4j-jdk14 dependency.

> LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. 
> Either remove Logback or the competing implementation (class org.slf4j.impl.JDK14LoggerFactory loaded from slf4j-jdk14-1.7.36.jar. 
>

**Comment by ljacomet** [comment] 2023-02-24 19:45
Thanks for your interest in this plugin

Would you be able to provide a reproducer?

Because from what I can tell, `slf4j-jdk14` shares a capability with `logback-classic` and when `enforceLogback()` is used, that capability conflict is resolved in favor of `logback-classic`.

See https://github.com/ljacomet/logging-capabilities/blob/d3899d1818814fe3e9ac21fb8bc537c7afef3267/src/main/java/dev/jacomet/gradle/plugins/logging/extension/LoggingCapabilitiesExtension.java#L56-L57

**Comment by ljacomet** [comment] 2023-04-22 15:36
I tried reproducing and failed.

Closing for now.

**Closed as not planned by ljacomet** 2023-04-22 15:36 UTC
Labels: invalid
